apiVersion: v1
kind: PersistentVolume
metadata:
  name: graylog-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: storage-graylog-data
  local:
    path: /mnt/disks/graylog-journal
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8node01