kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: graylog-data-pv
spec:
  storageClassName: storage-graylog-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi