apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  annotations:
    kompose.cmd: kompose -f docker-compose-metallb.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: http.host
          value: 0.0.0.0
        - name: network.host
          value: 0.0.0.0
        - name: transport.host
          value: localhost
        - name: xpack.security.enabled
          value: "false"
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.3
        name: elasticsearch
        resources:
          limits:
            memory: "1073741824"
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: es-data
      restartPolicy: Always
      volumes:
      - name: es-data
        persistentVolumeClaim:
          claimName: es-data-pv
status: {}
