apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose-general-example-persistent-data.yml
      convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
spec:
  ports:
  - name: elastic-api
    port: 55555
    targetPort: 0
  selector:
    io.kompose.service: elasticsearch
  type: LoadBalancer
  externalTrafficPolicy: Local
status:
  loadBalancer: {}
