apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose-general-example-persistent-data.yml
      convert -c
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: graylog
  name: graylog
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
  - name: "514"
    port: 514
    targetPort: 514
  - name: "513"
    port: 513
    protocol: UDP
    targetPort: 514
  - name: "12201"
    port: 12201
    targetPort: 12201
  - name: "12200"
    port: 12200
    protocol: UDP
    targetPort: 12201
  selector:
    io.kompose.service: graylog
status:
  loadBalancer: {}
