apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose-general-example-persistent-data.yml
      convert -c
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      containers:
      - image: mongo:3
        name: mongodb
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: docker-mongo-data
      restartPolicy: Always
      volumes:
      - name: docker-mongo-data
        persistentVolumeClaim:
          claimName: docker-mongo-data
status: {}
