apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f ../docker/docker-compose-general-example-persistent-data.yml
      convert
    kompose.version: 1.1.0 (36652f6)
  creationTimestamp: null
  labels:
    io.kompose.service: graylog
  name: graylog
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: graylog
    spec:
      containers:
      - env:
        - name: GRAYLOG_PASSWORD_SECRET
          value: somepasswordpepper
        - name: GRAYLOG_ROOT_PASSWORD_SHA2
          value: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
        - name: GRAYLOG_WEB_ENDPOINT_URI
          value: http://127.0.0.1:9000/api
        image: graylog/graylog:2.4.0-1
        name: graylog
        ports:
        - containerPort: 9000
        - containerPort: 514
        - containerPort: 514
          protocol: UDP
        - containerPort: 12201
        - containerPort: 12201
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/graylog/data/journal
          name: docker-graylog-journal
      restartPolicy: Always
      volumes:
      - name: docker-graylog-journal
        persistentVolumeClaim:
          claimName: docker-graylog-journal
status: {}
