apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo
  annotations:
    kompose.cmd: kompose -f docker-compose-metallb.yml convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongodb
    spec:
      hostname: mongo
      containers:
      - image: mongo:3
        name: mongo
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: mongo-data
      restartPolicy: Always
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-data-pv
status: {}
