kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-data-pv
spec:
  storageClassName: storage-mongo-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi